# Generated by Django 5.0.14 on 2026-09-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagegridblock",
            name="intro",
            field=models.TextField(
                blank=True, help_text="Optional lead paragraph shown above the grid."
            ),
        ),
    ]
