# Generated by Django 5.0.14 on 2026-09-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True, help_text="'About CRTDH' opening paragraph(s)."
                    ),
                ),
                ("mission_vision", models.TextField(blank=True)),
                ("ecosystem_heading", models.CharField(blank=True, max_length=255)),
                (
                    "ecosystem_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                (
                    "pi_desk_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                (
                    "pi_desk_document",
                    models.FileField(blank=True, null=True, upload_to="about/"),
                ),
                ("dsir_about", models.TextField(blank=True)),
                ("iitkgp_about", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "About page",
                "verbose_name_plural": "About page",
            },
        ),
        migrations.AddField(
            model_name="objectiverow",
            name="category",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_left",
            field=models.ImageField(blank=True, null=True, upload_to="brand/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_right",
            field=models.ImageField(blank=True, null=True, upload_to="brand/"),
        ),
        migrations.AlterField(
            model_name="objectiverow",
            name="outcome",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
