# Generated by Django 5.0.14 on 2026-09-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_aboutpage_objectiverow_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="focus_intro",
            field=models.TextField(
                blank=True,
                help_text="Short tagline(s) shown above the Focus Area color blocks, one per line.",
            ),
        ),
    ]
