# Generated by Django 5.0.14 on 2026-09-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_aboutpage_focus_intro"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objective_text", models.TextField(blank=True)),
                ("enterprises_text", models.TextField(blank=True)),
                (
                    "enterprises_image_1",
                    models.ImageField(blank=True, null=True, upload_to="home/"),
                ),
                (
                    "enterprises_image_2",
                    models.ImageField(blank=True, null=True, upload_to="home/"),
                ),
                (
                    "msme_map_image",
                    models.ImageField(blank=True, null=True, upload_to="home/"),
                ),
                (
                    "msme_caption",
                    models.CharField(
                        blank=True,
                        default="MSME cluster supported by CRTDH, IIT KGP",
                        max_length=255,
                    ),
                ),
                ("women_text_1", models.TextField(blank=True)),
                (
                    "women_image_1",
                    models.ImageField(blank=True, null=True, upload_to="home/"),
                ),
                (
                    "women_image_2",
                    models.ImageField(blank=True, null=True, upload_to="home/"),
                ),
                ("women_text_2", models.TextField(blank=True)),
                (
                    "location_address",
                    models.CharField(
                        blank=True,
                        default="Second Floor, Diamond Jubilee Building, IIT Kharagpur",
                        max_length=255,
                    ),
                ),
                (
                    "location_description",
                    models.TextField(
                        blank=True,
                        default="Available pilot plant and laboratories at CRTDH facility for research, MSME training and prototype development",
                    ),
                ),
                (
                    "facility_card_1_title",
                    models.CharField(
                        blank=True,
                        default="CRTDH Conference Room & Office",
                        max_length=255,
                    ),
                ),
                (
                    "facility_card_1_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/facility/"
                    ),
                ),
                ("facility_card_1_link", models.CharField(blank=True, max_length=255)),
                (
                    "facility_card_2_title",
                    models.CharField(
                        blank=True,
                        default="Pilot Plant and Manufacturing Units",
                        max_length=255,
                    ),
                ),
                (
                    "facility_card_2_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/facility/"
                    ),
                ),
                (
                    "facility_card_2_link",
                    models.CharField(
                        blank=True,
                        default="/facilities#manufacturing-plants",
                        max_length=255,
                    ),
                ),
                (
                    "facility_card_3_title",
                    models.CharField(
                        blank=True, default="CRTDH Sterile Room", max_length=255
                    ),
                ),
                (
                    "facility_card_3_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/facility/"
                    ),
                ),
                ("facility_card_3_link", models.CharField(blank=True, max_length=255)),
                (
                    "chintan_shivir_youtube_id",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "viksit_bharat_youtube_id",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "office_image",
                    models.ImageField(blank=True, null=True, upload_to="home/"),
                ),
                (
                    "membership_heading",
                    models.CharField(
                        blank=True,
                        default="Annual Membership for MSME / Startup",
                        max_length=255,
                    ),
                ),
                (
                    "membership_pdf",
                    models.FileField(blank=True, null=True, upload_to="home/"),
                ),
            ],
            options={
                "verbose_name": "Home page",
                "verbose_name_plural": "Home page",
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_logo",
            field=models.ImageField(blank=True, null=True, upload_to="brand/"),
        ),
    ]
