# Generated by Django 5.0.14 on 2026-09-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_homepage_sitesettings_site_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="map_embed_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
