# Generated by Django 5.0.14 on 2026-09-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesettings_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='in_more',
            field=models.BooleanField(default=False),
        ),
    ]
